
branches:
 only:
 - master
skip_tags: true

shallow_clone: false

version: 0.0.{build}
os:
  - Visual Studio 2017

environment:
  matrix:
    - APPLAUNCHER_CMAKE_GENERATOR: "Ninja"
      BLOCK: "0"

    - APPLAUNCHER_CMAKE_GENERATOR: "Visual Studio 15 2017"
      BLOCK: "0"

  PYTHON_DIR: "C:\\Python27-x64"
  PATH: "%PYTHON_DIR%;%PYTHON_DIR%\\Scripts;%PATH%"
  GITHUB_TOKEN:
    secure: 0D2ZkBwNKDnj7j9VNRaJlFCzmAYEHb3N+rzJdm+R4FDNh2P9HTqJ4NAtKm+9fXjw
  APPVEYOR_API_TOKEN:
    secure: U5fSDWJH39dwzLUfl7RZ0FwF+q7pK5tbAU8WGxO/1hc=

install:
  # Downloads and extract Qt static build
  - mkdir C:\Qt-static
  - ps: |
        $client = new-object System.Net.WebClient;
        $client.DownloadFile("https://github.com/jcfr/qt-static-build/releases/download/applauncher-5.11.2-vs2017/qt-5.11.2-static-ltcg-msvc2017-x86.zip", "C:\Qt-static\qt-5.11.2-static-ltcg-msvc2017-x86.zip")
        7z x C:\Qt-static\qt-5.11.2-static-ltcg-msvc2017-x86.zip -oC:\Qt-static\

build_script:
  - ps: |
        mkdir build
        cd build
  - ps: |
        $Qt5_DIR="C:\Qt-static\qt-5.11.2-static-ltcg-msvc2017-x86\lib\cmake\Qt5"
        $CTKAppLauncher_SOURCE_DIR=$pwd.Path + "\.."
        cmake `
          -DQt5_DIR:FILEPATH=$Qt5_DIR `
          -DCTKAppLauncher_SOURCE_DIR:PATH=$CTKAppLauncher_SOURCE_DIR `
          -P ..\msvc-static-configure.cmake
  # Build and package
  - ps: |
        cmake --build . --config Release --target PACKAGE

test_script:
  # Run tests
  - ps: |
        ctest -C Release -j4 -VV
  # Upload release and prerelease packages
  - ps: |
      pip install scikit-ci-addons==0.18.0
      ci_addons publish_github_release commontk/applauncher       `
        --exit-success-if-missing-token                           `
        --prerelease-packages CTKAppLauncher-*.tar.gz                `
        --prerelease-packages-clear-pattern "*win*"               `              `
        --prerelease-packages-keep-pattern "*<COMMIT_SHORT_SHA>*" `
        --release-packages CTKAppLauncher-*.tar.gz

on_finish:
  - pip install scikit-ci-addons
  - ci_addons --install ../
  - ps: ../appveyor/enable-worker-remote-access.ps1 -check_for_block
